sudo: false
language: node_js
node_js:
  - '10.17'
before_script: npm run build

matrix:
  include:
    - name: "Unit tests and coverage"
      script: npm run coverage

    - name: "Test e2e:sdk"
      script: npm run test:e2e:sdk

    - name: "Test e2e:polymer2"
      script: npm run test:e2e:polymer2

    - name: "Test e2e:polymer2-ts"
      script: npm run test:e2e:polymer2-ts

    - name: "Test e2e:react:scr"
      script: npm run test:e2e:react:scr

    - name: "Test e2e:react:scr os: windows"
      os:
        - windows
      script: npx mocha 'test\e2e\react-client--scr.test.js'  -g 'test:e2e:react:scr' --timeout 0

    - name: "Test e2e:react:new-project"
      script: npm run test:e2e:react:new-project

    - name: "Test e2e:react:empty-model"
      script: npm run test:e2e:react:empty-model
